version: 2
jobs:
  build_and_test:
    docker:
      image: node:10-alpine
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: coverage
          command: npm run coverage 
      - run:
          name: test
          command: npm run test
      - run:
          name: upload coverage
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
