version: 2
jobs:
  build_and_test:
    docker:
      image: node:10-alpine
    steps:
      - checkout
      - run:
          name: install
          command: yarn install
      - run:
          name: test
          command: yarn test
      - run:
          name: upload coverage
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
